services:
  - type: web
    name: miapp2026
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8080
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"